name: Deploy dokku
on:
    push:
        branches:
            - main
        paths:
        - 'backend/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Dokku deploy
              uses: vitalyliber/dokku-github-action@v4.0
              env:
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                  HOST: api.opentrackmania.com
                  PROJECT: parkkihubi
